#!/usr/bin/env python
#
# KEISER 2018-06-08
#
# Script to parse myNCBI My Bibliography medline export to jekyll page MD

import argparse
import csv
import datetime
import itertools
from Bio import Medline
import yaml

DEF_OUTFILE = "publications.md"
DOI_URLBASE = "https://doi.org"
PMID_URLBASE = "https://www.ncbi.nlm.nih.gov/pubmed"

# Publication row columns (internal list-of-lists used throughout main())
COL_PID = 0
COL_TITLE = 1
COL_JOURNAL = 2
COL_DATE = 3
COL_AUTHORS = 4
COL_URL = 5
COL_DOI = 6
COL_PREPRINT = 7       # tuple (url, label) or None
COL_JEKYLL_DATE = 8
COL_TYPE = 9
COL_EXTRA_LINKS = 10   # list of {kind, url, label, [icon]}

# Output templates remain unchanged
PG_HDR = """---
# this is autogenerated: do not edit
title: Publications
layout: splash
permalink: /publications/
excerpt: "Selected lab publications, with links to preprints and supporting content."
tags: [publications, papers, preprints, manuscripts]
header:
   image: /assets/images/bar-network.png
intro:
    - title: Publications
{feature_rows}
---
{{% include feature_row id="intro" type="center" %}}
"""

F_ROW_HDR = """feature_row{row_num}:
{items}
"""

F_ROW_ITEM = """
  - image_path: /assets/images/papers/{image}
    alt: >-
        {alt}
    title: >-
        {title}
    excerpt: >-
        {excerpt}
    url: "{url}"
    doi: "{doi}"
    btn_label: >-
        doi &nbsp; <i class="fas fa-external-link-alt"></i>
    btn_class: "btn--primary"
{preprint}{extra_links}"""

F_ROW_PREPRINT = """    url2: "{url}"
    btn2_label: >-
        {label} &nbsp; <i class="fas fa-external-link-alt"></i>
    btn2_class: "btn--info"
"""

F_ROW_EXTRA_LINKS_HDR = "    extra_links:\n"

F_ROW_EXTRA_LINK = """      - kind: {kind}
        url: "{url}"
        label: "{label}"
"""

F_ROW_EXTRA_LINK_ICON = '        icon: "{icon}"\n'

F_ROW_INCL = """
<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>

{{% include feature_row_paper.html id="feature_row{row_num}" %}}
"""

PAPER_TEMPLATE = """<span itemprop="isPartOf" itemscope itemtype="http://schema.org/Periodical"><strong>{journal}</strong></span>. \
<span itemprop="datePublished">{date}</span>. \
<span itemprop="author">{authors}</span>."""

CSV_HEADER = [
    "id",
    "title",
    "journal",
    "date",
    "authors",
    "link",
    "doi_suffix",
    "preprint_url",
    "preprint_journal",
    "jekyll_date",
    "type",
]

MAX_AUTHORS = 10  # threshold to trigger truncation
KEEP_FIRST = 3
KEEP_LAST = 3


def truncate_authors(authors_str):
    "truncate long author lists to first N + last N with ellipsis"
    authors = [a.strip() for a in authors_str.split(",")]
    if len(authors) <= MAX_AUTHORS:
        return authors_str
    kept = authors[:KEEP_FIRST] + ["..."] + authors[-KEEP_LAST:]
    return ", ".join(kept)


def make_htmlsafe(txt):
    "make text html safe (primitive)"
    dangerlist = {'"': "&quot;"}
    for d, r in dangerlist.items():
        txt = txt.replace(d, r)
    return txt


def grouper(n, iterable, fillvalue=None):
    "grouper(3, 'ABCDEFG', 'x') --> ABC DEF Gxx"
    args = [iter(iterable)] * n
    return itertools.zip_longest(*args, fillvalue=fillvalue)


def aid_scrub(aid):
    "put a AID (e.g., DOI) into filename compatible format"
    return aid.replace("/", ".")


def get_id_url(record):
    "pull DOI if possible, otherwise PMID: return (id, url, doi)"
    if "AID" in record:
        aid = list(filter(lambda x: x.lower().find("doi") != -1, record["AID"]))
        assert len(aid) == 1
        aid = aid[0].split()[0]
        print(f"\tdoi {aid}")
        return aid_scrub(aid), f"{DOI_URLBASE}/{aid}", aid
    else:
        pmid = record["PMID"]
        print(f"\tpmid {pmid}")
        return pmid, f"{PMID_URLBASE}/{pmid}", ""


def convert_date(datestr):
    "convert YYYY Mon Day format into Jekyll post date format"
    try:
        return datetime.datetime.strptime(datestr, "%Y %b %d").strftime("%Y-%m-%d")
    except ValueError:
        try:
            return datetime.datetime.strptime(datestr, "%Y %b").strftime("%Y-%m-%d")
        except ValueError:
            return datetime.datetime.strptime(datestr, "%Y").strftime("%Y-%m-%d")


PREPRINT_DOI_PREFIXES = ("10.1101/", "10.26434/")


def is_preprint_doi(doi):
    "check if a DOI belongs to a preprint server (bioRxiv, chemRxiv)"
    return doi.startswith(PREPRINT_DOI_PREFIXES)


def load_skip_list(fskip):
    "load set of DOIs to skip from a CSV file with a 'doi' column"
    if fskip is None:
        return set()
    with open(fskip) as fi:
        reader = csv.DictReader(fi)
        return {row["doi"] for row in reader}


def load_supplemental(path):
    """Parse supplemental.yml into (standalone_records, supplemental_map).

    standalone_records: list of dicts (one per preprint not indexed by PubMed)
        {journal, journal_id, authors, title, pub_date, url, doi, [links]}
    supplemental_map: {doi: {"preprint": {url, label} | None, "links": [...]}}
    """
    with open(path) as fi:
        data = yaml.safe_load(fi) or {}
    standalones = data.get("standalone_preprints") or []
    raw_supp = data.get("supplemental") or {}
    supplemental = {}
    for doi, entry in raw_supp.items():
        entry = entry or {}
        supplemental[doi] = {
            "preprint": entry.get("preprint"),
            "links": entry.get("links") or [],
        }
    return standalones, supplemental


def render_extra_links(links):
    "render an extra_links list as a YAML block (or empty string if no links)"
    if not links:
        return ""
    out = [F_ROW_EXTRA_LINKS_HDR]
    for link in links:
        out.append(
            F_ROW_EXTRA_LINK.format(
                kind=link["kind"],
                url=link["url"],
                label=link["label"],
            )
        )
        if link.get("icon"):
            out.append(F_ROW_EXTRA_LINK_ICON.format(icon=link["icon"]))
    return "".join(out)


def main(fmedline, fsupplemental, outfile, datafile, fmanual, fskip=None):
    skip_dois = load_skip_list(fskip)
    if skip_dois:
        print(f"skip list: {len(skip_dois)} dois")

    standalones, supplemental_map = load_supplemental(fsupplemental)
    print(
        f"read {len(standalones) + len(supplemental_map)} supplemental records, "
        f"{len(supplemental_map)} keyed by doi"
    )

    with open(fmedline) as fi:
        m_records = list(Medline.parse(fi))
    if fmanual is not None:
        with open(fmanual) as fm:
            m_records.extend(list(Medline.parse(fm)))

    publications = []
    # Standalone preprints first (not in PubMed)
    for rec in standalones:
        pid = ".".join([rec["journal"].replace(" ", "_"), rec["journal_id"]])
        publications.append(
            [
                pid,
                make_htmlsafe(rec["title"]),
                rec["journal"],
                rec["pub_date"],
                rec["authors"],
                "",
                rec["doi"],
                (rec["url"], rec["journal"]),
                convert_date(rec["pub_date"]),
                "preprint",
                rec.get("links") or [],
            ]
        )

    n_skipped_preprint = 0
    n_skipped_list = 0
    for record in m_records:
        aid, url, doi = get_id_url(record)
        if doi and is_preprint_doi(doi):
            n_skipped_preprint += 1
            print("\tskipped: preprint doi in medline")
            continue
        if doi in skip_dois:
            n_skipped_list += 1
            print("\tskipped: in skip list")
            continue
        supp = supplemental_map.get(doi) or {}
        pp = supp.get("preprint")
        pprint = (pp["url"], pp["label"]) if pp else None
        extra_links = supp.get("links") or []
        publications.append(
            [
                aid,
                make_htmlsafe(record["TI"].strip(".")),
                record["TA"],
                record["DP"],
                ", ".join(record["AU"]),
                url,
                doi,
                pprint,
                convert_date(record["DP"]),
                "ncbi",
                extra_links,
            ]
        )
    if n_skipped_preprint:
        print(
            f"skipped {n_skipped_preprint} preprint medline records (supplemental.yml is SSOT)"
        )
    if n_skipped_list:
        print(f"skipped {n_skipped_list} records via skip list")

    publications.sort(key=lambda x: x[COL_JEKYLL_DATE], reverse=True)

    n_expected = len(standalones) + len(m_records) - n_skipped_preprint - n_skipped_list
    print(f"read {len(m_records)} medline records")
    print(
        f"merged into {len(publications)} publication entries (expected {n_expected})"
    )

    frows = []
    for i, p3 in enumerate(grouper(3, publications)):
        items = []
        for p in filter(None, p3):
            pp = p[COL_PREPRINT]
            pprint = (
                F_ROW_PREPRINT.format(url=pp[0], label=pp[1]) if pp is not None else ""
            )
            extra = render_extra_links(p[COL_EXTRA_LINKS])
            items.append(
                F_ROW_ITEM.format(
                    image=f"{p[COL_PID]}.jpg",
                    alt=p[COL_TITLE],
                    title=f'<span itemprop="name">{p[COL_TITLE]}</span>',
                    excerpt=PAPER_TEMPLATE.format(
                        journal=p[COL_JOURNAL],
                        date=p[COL_DATE],
                        authors=truncate_authors(p[COL_AUTHORS]),
                    ),
                    url=p[COL_URL],
                    doi=p[COL_DOI],
                    preprint=pprint,
                    extra_links=extra,
                )
            )
        frows.append(F_ROW_HDR.format(row_num=i, items="".join(items)))

    with open(outfile, "w", encoding="utf-8") as fo:
        fo.write(PG_HDR.format(feature_rows="".join(frows)))
        for i in range(len(frows)):
            fo.write(F_ROW_INCL.format(row_num=i))

    if datafile is not None:
        print(f"outputting structured papers to {datafile} as well")
        with open(datafile, "w", newline="", encoding="utf-8") as fo:
            writer = csv.writer(fo)
            writer.writerow(CSV_HEADER)
            for row in publications:
                row1 = row[:COL_PREPRINT]
                row2 = row[COL_JEKYLL_DATE : COL_EXTRA_LINKS]
                pp = row[COL_PREPRINT]
                pp = list(pp) if pp is not None else ["", ""]
                writer.writerow(row1 + pp + row2)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Parse myNCBI My Bibliography medline export to jekyll page MD"
    )

    parser.add_argument("myncbi_file", help="Input NBIB file from myNCBI")
    parser.add_argument(
        "supplemental_file",
        help="Input YAML file with standalone preprints and per-doi enrichments",
    )

    parser.add_argument(
        "-o",
        "--outfile",
        default=DEF_OUTFILE,
        help=f"Output file (default: {DEF_OUTFILE})",
    )

    parser.add_argument(
        "-d", "--datafile", help="Output copy of structured data to CSV file"
    )

    parser.add_argument(
        "-m", "--manual", help="Manual MEDLINE/NBIB file for articles not in PubMed"
    )

    parser.add_argument(
        "-s", "--skip", help='CSV file with DOIs to skip (must have a "doi" column)'
    )

    args = parser.parse_args()

    main(
        args.myncbi_file,
        args.supplemental_file,
        args.outfile,
        args.datafile,
        args.manual,
        args.skip,
    )
