#!/usr/bin/env python
#
# KEISER 2018-06-08
#
# Script to parse myNCBI My Bibliography medline export to jekyll page MD

import argparse
import csv
import datetime
import itertools
import json
from Bio import Medline
import yaml

DEF_OUTFILE = "publications.md"
DOI_URLBASE = "https://doi.org"
PMID_URLBASE = "https://www.ncbi.nlm.nih.gov/pubmed"

# Publication row columns (internal list-of-lists used throughout main())
COL_PID = 0
COL_TITLE = 1
COL_JOURNAL = 2
COL_DATE = 3
COL_AUTHORS = 4
COL_URL = 5
COL_DOI = 6
COL_PREPRINT = 7  # tuple (url, label) or None
COL_JEKYLL_DATE = 8
COL_TYPE = 9
COL_EXTRA_LINKS = 10  # list of {kind, url, label, [icon]}

# Output templates remain unchanged
PG_HDR = """---
# this is autogenerated: do not edit
title: Publications
layout: splash
permalink: /publications/
excerpt: "Selected lab publications, with links to preprints and supporting content."
tags: [publications, papers, preprints, manuscripts]
header:
   image: /assets/images/bar-network.png
{feature_rows}
---
{publications_jsonld}

# Publications

"""

F_ROW_HDR = """feature_row{row_num}:
{items}
"""

F_ROW_ITEM = """
  - image_path: /assets/images/papers/{image}
    alt: >-
        {alt}
    title: >-
        {title}
    excerpt: >-
        {excerpt}
    url: "{url}"
    doi: "{doi}"
    btn_label: >-
        <i class="fas fa-book-open"></i>&nbsp; doi
    btn_class: "btn--info"
{preprint}{extra_links}"""

F_ROW_PREPRINT = """    url2: "{url}"
    btn2_label: >-
        <i class="{icon}"></i>&nbsp; {label}
    btn2_class: "btn--success"
"""


def preprint_icon(label):
    "pick an icon class for a preprint server based on its journal label"
    lower = (label or "").lower()
    if "biorxiv" in lower:
        return "ai ai-biorxiv"
    if "chemrxiv" in lower:
        # academicons has no dedicated chemRxiv glyph; use a chemistry-themed FA icon
        return "fas fa-atom"
    if "arxiv" in lower:
        return "ai ai-arxiv"
    return "fas fa-file-alt"


_PREPRINT_PREFIXES = ("arxiv - ", "biorxiv - ", "chemrxiv - ")


def preprint_display_label(label):
    """Strip '<server> - ' prefix when the preprint icon disambiguates the platform.

    'arXiv - NeurIPS ML4H'      -> 'NeurIPS ML4H'
    'bioRxiv - NeurIPS LMRL'    -> 'NeurIPS LMRL'
    'bioRxiv' (no suffix)       -> 'bioRxiv'
    """
    if not label:
        return label
    lower = label.lower()
    for prefix in _PREPRINT_PREFIXES:
        if lower.startswith(prefix):
            return label[len(prefix) :]
    return label


F_ROW_EXTRA_LINKS_HDR = "    extra_links:\n"

F_ROW_EXTRA_LINK = """      - kind: {kind}
        url: "{url}"
        label: "{label}"
"""

F_ROW_EXTRA_LINK_ROLE = "        role: {role}\n"
F_ROW_EXTRA_LINK_ICON = '        icon: "{icon}"\n'

F_ROW_INCL = """
{{% include feature_row_paper.html id="feature_row{row_num}" %}}
"""

# Resources page (code & data landing) templates
R_PG_HDR = """---
# this is autogenerated: do not edit
layout: single
title: Code &amp; Data
permalink: /resources/
excerpt: "Code, tools, and datasets released alongside lab publications"
tags: [resources, code, data, repositories, datasets, tools]
modified:
comments: false
header:
   image: /assets/images/bar-network.png
---
{resources_jsonld}

The lab's full public code archive lives at [**github.com/keiserlab**](https://github.com/keiserlab) <i class="fab fa-github"></i>. The table below lists code and data released alongside lab publications, newest first. For the complete citation list see the [publications page](/publications/).

| Paper | Tool | Paper code | Data |
|---|---|---|---|
{rows}"""

R_ROW = "| {paper} | {tool} | {paper_repo} | {data} |\n"

PAPER_TEMPLATE = """<span itemprop="isPartOf" itemscope itemtype="http://schema.org/Periodical"><strong>{journal}</strong></span>. \
<span itemprop="datePublished">{date}</span>. \
<span itemprop="author">{authors}</span>."""

CSV_HEADER = [
    "id",
    "title",
    "journal",
    "date",
    "authors",
    "link",
    "doi_suffix",
    "preprint_url",
    "preprint_journal",
    "jekyll_date",
    "type",
]

MAX_AUTHORS = 10  # threshold to trigger truncation
KEEP_FIRST = 3
KEEP_LAST = 3


def truncate_authors(authors_str):
    "truncate long author lists to first N + last N with ellipsis"
    authors = [a.strip() for a in authors_str.split(",")]
    if len(authors) <= MAX_AUTHORS:
        return authors_str
    kept = authors[:KEEP_FIRST] + ["..."] + authors[-KEEP_LAST:]
    return ", ".join(kept)


def truncate_author_list(authors_str):
    "like truncate_authors but return the name list without the '...' marker"
    authors = [a.strip() for a in authors_str.split(",") if a.strip()]
    if len(authors) <= MAX_AUTHORS:
        return authors
    return authors[:KEEP_FIRST] + authors[-KEEP_LAST:]


def make_htmlsafe(txt):
    "make text html safe (primitive)"
    dangerlist = {'"': "&quot;"}
    for d, r in dangerlist.items():
        txt = txt.replace(d, r)
    return txt


def grouper(n, iterable, fillvalue=None):
    "grouper(3, 'ABCDEFG', 'x') --> ABC DEF Gxx"
    args = [iter(iterable)] * n
    return itertools.zip_longest(*args, fillvalue=fillvalue)


def aid_scrub(aid):
    "put a AID (e.g., DOI) into filename compatible format"
    return aid.replace("/", ".")


def get_id_url(record):
    "pull DOI if possible, otherwise PMID: return (id, url, doi)"
    if "AID" in record:
        aid = list(filter(lambda x: x.lower().find("doi") != -1, record["AID"]))
        assert len(aid) == 1
        aid = aid[0].split()[0]
        print(f"\tdoi {aid}")
        return aid_scrub(aid), f"{DOI_URLBASE}/{aid}", aid
    else:
        pmid = record["PMID"]
        print(f"\tpmid {pmid}")
        return pmid, f"{PMID_URLBASE}/{pmid}", ""


def convert_date(datestr):
    "convert YYYY Mon Day format into Jekyll post date format"
    try:
        return datetime.datetime.strptime(datestr, "%Y %b %d").strftime("%Y-%m-%d")
    except ValueError:
        try:
            return datetime.datetime.strptime(datestr, "%Y %b").strftime("%Y-%m-%d")
        except ValueError:
            return datetime.datetime.strptime(datestr, "%Y").strftime("%Y-%m-%d")


PREPRINT_DOI_PREFIXES = ("10.1101/", "10.26434/")


def is_preprint_doi(doi):
    "check if a DOI belongs to a preprint server (bioRxiv, chemRxiv)"
    return doi.startswith(PREPRINT_DOI_PREFIXES)


def load_skip_list(fskip):
    "load set of DOIs to skip from a CSV file with a 'doi' column"
    if fskip is None:
        return set()
    with open(fskip) as fi:
        reader = csv.DictReader(fi)
        return {row["doi"] for row in reader}


def load_supplemental(path):
    """Parse supplemental.yml into (standalone_records, supplemental_map, orphan_tools).

    standalone_records: list of dicts (one per preprint not indexed by PubMed)
        {journal, journal_id, authors, title, pub_date, url, doi, [links]}
    supplemental_map: {doi: {"preprint": {url, label} | None, "links": [...]}}
    orphan_tools: list of {url, label, description} for tools with no paper
    """
    with open(path) as fi:
        data = yaml.safe_load(fi) or {}
    standalones = data.get("standalone_preprints") or []
    raw_supp = data.get("supplemental") or {}
    supplemental = {}
    for doi, entry in raw_supp.items():
        entry = entry or {}
        supplemental[doi] = {
            "preprint": entry.get("preprint"),
            "links": entry.get("links") or [],
        }
    orphan_tools = data.get("orphan_tools") or []
    return standalones, supplemental, orphan_tools


def first_author_etal(authors_str):
    "short-form author string for the resources table"
    authors = [a.strip() for a in authors_str.split(",") if a.strip()]
    if not authors:
        return ""
    if len(authors) == 1:
        return authors[0]
    return f"{authors[0]} et al."


DATA_ICONS = {
    "zenodo": "ai ai-zenodo",
    "osf": "ai ai-osf",
    "figshare": "ai ai-figshare",
    "dryad": "ai ai-dryad",
    "mendeley": "ai ai-mendeley",
}


def link_icon(link, default_icon):
    "pick a font-awesome or academicon class for a link"
    if link.get("icon"):
        return link["icon"]
    if link.get("kind") == "data":
        return DATA_ICONS.get(link.get("label", "").lower(), default_icon)
    return default_icon


def _jsonld_script(doc):
    "wrap a python dict as a script tag containing JSON-LD"
    body = json.dumps(doc, ensure_ascii=False, indent=2)
    return '<script type="application/ld+json">\n' + body + "\n</script>"


def _canonical_doi_url(doi):
    "return a canonical https://doi.org/ URL for a DOI string"
    if not doi:
        return None
    if doi.lower().startswith("http"):
        return doi
    return f"https://doi.org/{doi}"


def _article_is_part_of(p):
    """Build a schema.org reference back to a publication for isPartOf fields."""
    ref = {"@type": "ScholarlyArticle", "name": p[COL_TITLE]}
    doi = p[COL_DOI]
    if doi:
        ref["identifier"] = f"doi:{doi}"
    url = p[COL_URL] or None
    if not url and p[COL_PREPRINT] is not None:
        url = p[COL_PREPRINT][0]
    if url:
        ref["url"] = url
    return ref


def render_publications_jsonld(publications):
    """Emit a single <script type='application/ld+json'> with an ItemList of
    ScholarlyArticle entries, one per publication (in the same reverse-chron
    order the page renders them)."""
    items = []
    for i, p in enumerate(publications, start=1):
        authors = truncate_author_list(p[COL_AUTHORS])
        article = {
            "@type": "ScholarlyArticle",
            "headline": p[COL_TITLE],
            "author": [{"@type": "Person", "name": a} for a in authors],
            "datePublished": p[COL_JEKYLL_DATE],
            "isPartOf": {"@type": "Periodical", "name": p[COL_JOURNAL]},
        }
        doi = p[COL_DOI]
        if doi:
            article["identifier"] = f"doi:{doi}"
            article["@id"] = _canonical_doi_url(doi)
        url = p[COL_URL] or None
        if not url and p[COL_PREPRINT] is not None:
            url = p[COL_PREPRINT][0]
        if url:
            article["url"] = url
        pp = p[COL_PREPRINT]
        if pp is not None and pp[0] != url:
            article["sameAs"] = pp[0]
        code_urls = [
            link["url"] for link in p[COL_EXTRA_LINKS] if link.get("kind") == "code"
        ]
        if code_urls:
            article["codeRepository"] = (
                code_urls[0] if len(code_urls) == 1 else code_urls
            )
        items.append(
            {"@type": "ListItem", "position": i, "item": article}
        )
    doc = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Keiser Lab publications",
        "numberOfItems": len(items),
        "itemListElement": items,
    }
    return _jsonld_script(doc)


def render_resources_jsonld(publications, orphan_tools):
    """Emit a JSON-LD @graph of SoftwareSourceCode and Dataset entities for
    every code/data link in the publications, plus standalone SoftwareSourceCode
    entries for orphan tools."""
    graph = []
    for p in publications:
        links = p[COL_EXTRA_LINKS]
        if not links:
            continue
        is_part_of = _article_is_part_of(p)
        for link in links:
            kind = link.get("kind")
            label = link.get("label", "")
            url = link["url"]
            if kind == "code":
                graph.append(
                    {
                        "@type": "SoftwareSourceCode",
                        "name": label or "Code",
                        "codeRepository": url,
                        "url": url,
                        "isPartOf": is_part_of,
                    }
                )
            elif kind == "data":
                graph.append(
                    {
                        "@type": "Dataset",
                        "name": label or "Dataset",
                        "url": url,
                        "isPartOf": is_part_of,
                    }
                )
    for tool in orphan_tools:
        entry = {
            "@type": "SoftwareSourceCode",
            "name": tool.get("label", "tool"),
            "codeRepository": tool["url"],
            "url": tool["url"],
        }
        desc = tool.get("description")
        if desc:
            entry["description"] = desc
        graph.append(entry)
    doc = {
        "@context": "https://schema.org",
        "@graph": graph,
    }
    return _jsonld_script(doc)


def render_resources_cell(links, default_icon, drop_label=False):
    "render a list of links as a <br>-joined markdown cell (em-dash if empty)"
    if not links:
        return "&mdash;"
    parts = []
    for link in links:
        icon = link_icon(link, default_icon)
        if drop_label:
            parts.append(f'[<i class="{icon}"></i>]({link["url"]})')
        else:
            parts.append(f'[<i class="{icon}"></i> {link["label"]}]({link["url"]})')
    return "<br>".join(parts)


def render_resources_page(publications, orphan_tools, outfile):
    "emit the /resources/ landing page as a markdown table"
    rows = []
    for p in publications:
        links = p[COL_EXTRA_LINKS]
        tool_links = [
            link
            for link in links
            if link.get("kind") == "code" and link.get("role") == "tool"
        ]
        paper_links = [
            link
            for link in links
            if link.get("kind") == "code" and link.get("role") != "tool"
        ]
        data_links = [link for link in links if link.get("kind") == "data"]

        # Only include papers with at least one code/data link
        if not (tool_links or paper_links or data_links):
            continue

        # Paper cell: title (linked to DOI or standalone url) + short citation
        title = p[COL_TITLE]
        url = p[COL_URL]
        if not url and p[COL_PREPRINT] is not None:
            url = p[COL_PREPRINT][0]
        year = p[COL_JEKYLL_DATE][:4]
        citation = f"*{first_author_etal(p[COL_AUTHORS])}*, **{p[COL_JOURNAL]}** {year}"
        paper_cell = f"[{title}]({url})<br>{citation}"

        rows.append(
            R_ROW.format(
                paper=paper_cell,
                tool=render_resources_cell(tool_links, "fab fa-github"),
                paper_repo=render_resources_cell(
                    paper_links, "fab fa-github", drop_label=True
                ),
                data=render_resources_cell(data_links, "fas fa-database"),
            )
        )

    # Append orphan tool rows — standalone projects with no paper.
    for tool in orphan_tools:
        paper_cell = f"**[Project]** {tool.get('description', '')}"
        tool_cell = f'[<i class="fab fa-github"></i> {tool["label"]}]({tool["url"]})'
        rows.append(
            R_ROW.format(
                paper=paper_cell,
                tool=tool_cell,
                paper_repo="&mdash;",
                data="&mdash;",
            )
        )

    with open(outfile, "w", encoding="utf-8") as fo:
        fo.write(
            R_PG_HDR.format(
                rows="".join(rows),
                resources_jsonld=render_resources_jsonld(publications, orphan_tools),
            )
        )
    print(f"wrote {len(rows)} resource rows to {outfile}")


def render_extra_links(links):
    "render an extra_links list as a YAML block (or empty string if no links)"
    if not links:
        return ""
    out = [F_ROW_EXTRA_LINKS_HDR]
    for link in links:
        out.append(
            F_ROW_EXTRA_LINK.format(
                kind=link["kind"],
                url=link["url"],
                label=link["label"],
            )
        )
        if link.get("role"):
            out.append(F_ROW_EXTRA_LINK_ROLE.format(role=link["role"]))
        if link.get("icon"):
            out.append(F_ROW_EXTRA_LINK_ICON.format(icon=link["icon"]))
    return "".join(out)


def main(
    fmedline, fsupplemental, outfile, datafile, fmanual, fskip=None, fresources=None
):
    skip_dois = load_skip_list(fskip)
    if skip_dois:
        print(f"skip list: {len(skip_dois)} dois")

    standalones, supplemental_map, orphan_tools = load_supplemental(fsupplemental)
    print(
        f"read {len(standalones) + len(supplemental_map)} supplemental records, "
        f"{len(supplemental_map)} keyed by doi, "
        f"{len(orphan_tools)} orphan tools"
    )

    with open(fmedline) as fi:
        m_records = list(Medline.parse(fi))
    if fmanual is not None:
        with open(fmanual) as fm:
            m_records.extend(list(Medline.parse(fm)))

    publications = []
    # Standalone preprints first (not in PubMed)
    for rec in standalones:
        pid = ".".join([rec["journal"].replace(" ", "_"), rec["journal_id"]])
        publications.append(
            [
                pid,
                make_htmlsafe(rec["title"]),
                rec["journal"],
                rec["pub_date"],
                rec["authors"],
                "",
                rec["doi"],
                (rec["url"], rec["journal"]),
                convert_date(rec["pub_date"]),
                "preprint",
                rec.get("links") or [],
            ]
        )

    n_skipped_preprint = 0
    n_skipped_list = 0
    for record in m_records:
        aid, url, doi = get_id_url(record)
        if doi and is_preprint_doi(doi):
            n_skipped_preprint += 1
            print("\tskipped: preprint doi in medline")
            continue
        if doi in skip_dois:
            n_skipped_list += 1
            print("\tskipped: in skip list")
            continue
        supp = supplemental_map.get(doi) or {}
        pp = supp.get("preprint")
        pprint = (pp["url"], pp["label"]) if pp else None
        extra_links = supp.get("links") or []
        publications.append(
            [
                aid,
                make_htmlsafe(record["TI"].strip(".")),
                record["TA"],
                record["DP"],
                ", ".join(record["AU"]),
                url,
                doi,
                pprint,
                convert_date(record["DP"]),
                "ncbi",
                extra_links,
            ]
        )
    if n_skipped_preprint:
        print(
            f"skipped {n_skipped_preprint} preprint medline records (supplemental.yml is SSOT)"
        )
    if n_skipped_list:
        print(f"skipped {n_skipped_list} records via skip list")

    publications.sort(key=lambda x: x[COL_JEKYLL_DATE], reverse=True)

    n_expected = len(standalones) + len(m_records) - n_skipped_preprint - n_skipped_list
    print(f"read {len(m_records)} medline records")
    print(
        f"merged into {len(publications)} publication entries (expected {n_expected})"
    )

    frows = []
    for i, p3 in enumerate(grouper(3, publications)):
        items = []
        for p in filter(None, p3):
            pp = p[COL_PREPRINT]
            pprint = (
                F_ROW_PREPRINT.format(
                    url=pp[0],
                    label=preprint_display_label(pp[1]),
                    icon=preprint_icon(pp[1]),
                )
                if pp is not None
                else ""
            )
            extra = render_extra_links(p[COL_EXTRA_LINKS])
            items.append(
                F_ROW_ITEM.format(
                    image=f"{p[COL_PID]}.jpg",
                    alt=p[COL_TITLE],
                    title=f'<span itemprop="name">{p[COL_TITLE]}</span>',
                    excerpt=PAPER_TEMPLATE.format(
                        journal=p[COL_JOURNAL],
                        date=p[COL_DATE],
                        authors=truncate_authors(p[COL_AUTHORS]),
                    ),
                    url=p[COL_URL],
                    doi=p[COL_DOI],
                    preprint=pprint,
                    extra_links=extra,
                )
            )
        frows.append(F_ROW_HDR.format(row_num=i, items="".join(items)))

    with open(outfile, "w", encoding="utf-8") as fo:
        fo.write(
            PG_HDR.format(
                feature_rows="".join(frows),
                publications_jsonld=render_publications_jsonld(publications),
            )
        )
        for i in range(len(frows)):
            fo.write(F_ROW_INCL.format(row_num=i))

    if datafile is not None:
        print(f"outputting structured papers to {datafile} as well")
        with open(datafile, "w", newline="", encoding="utf-8") as fo:
            writer = csv.writer(fo)
            writer.writerow(CSV_HEADER)
            for row in publications:
                row1 = row[:COL_PREPRINT]
                row2 = row[COL_JEKYLL_DATE:COL_EXTRA_LINKS]
                pp = row[COL_PREPRINT]
                pp = list(pp) if pp is not None else ["", ""]
                writer.writerow(row1 + pp + row2)

    if fresources is not None:
        render_resources_page(publications, orphan_tools, fresources)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Parse myNCBI My Bibliography medline export to jekyll page MD"
    )

    parser.add_argument("myncbi_file", help="Input NBIB file from myNCBI")
    parser.add_argument(
        "supplemental_file",
        help="Input YAML file with standalone preprints and per-doi enrichments",
    )

    parser.add_argument(
        "-o",
        "--outfile",
        default=DEF_OUTFILE,
        help=f"Output file (default: {DEF_OUTFILE})",
    )

    parser.add_argument(
        "-d", "--datafile", help="Output copy of structured data to CSV file"
    )

    parser.add_argument(
        "-m", "--manual", help="Manual MEDLINE/NBIB file for articles not in PubMed"
    )

    parser.add_argument(
        "-s", "--skip", help='CSV file with DOIs to skip (must have a "doi" column)'
    )

    parser.add_argument(
        "-r",
        "--resources",
        help="Output path for the auto-generated resources.md landing page",
    )

    args = parser.parse_args()

    main(
        args.myncbi_file,
        args.supplemental_file,
        args.outfile,
        args.datafile,
        args.manual,
        args.skip,
        args.resources,
    )
